name: Build Docker Image for Synology

on:
  release:
    types: [published]
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          tags: mrg-share:latest
          outputs: type=docker,dest=/tmp/mrg-share.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: mrg-share-docker-image
          path: /tmp/mrg-share.tar
          retention-days: 30