name: Build Docker Image for Synology

on:
  release:
    types: [published]
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          tags: mrg-share:${{ github.run_number }}
          outputs: type=docker,dest=/tmp/mrg-share-${{ github.run_number }}.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mrg-share-docker-image-${{ github.run_number }}
          path: /tmp/mrg-share-${{ github.run_number }}.tar
          retention-days: 30